api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true
  insecure: true


log:
  level: "DEBUG"

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https


  websecure:
    address: ":443"

  mysql:
    address: ":3306/tcp"


providers:
  docker: true
